### PR TITLE
[Accessibility] Make active box distinguishable

### PR DESCRIPTION
**Pull request by kylo252**
Minor tweak to make it easier to tell when the search-box is active

*This change only applies to the dark theme*

### CODE REVIEW

**Comment by Horst12** [comment]
For me activating the search box is changes its background form black to white and the text from white to black.
What is the problem in your case to see that it is avtivated.
Also it never gets activated by accident so you always have clicked on it or hit the hotkey.

**Comment by kylo252** [comment]
Hmmm I'm not sure I follow, but here's what it looks like for me: 
Original:
original 
vs 
Modified:
modified

EverythingToolbar-0.6.0-beta3

**Comment by Horst12** [comment]
Here how its looks for me
Activated
Screenshot - 25 12 2020 , 17_22_10
Default
Screenshot - 25 12 2020 , 17_21_56

**Comment by kylo252** [comment]
I'm guessing you're using [Medium](https://github.com/stnkl/EverythingToolbar/blob/master/EverythingToolbar/Themes/Medium.xaml#L10-L11) theme, see how it has different values for Hover/Active
```xaml
    <SolidColorBrush x:Key="SearchBoxWatermarkForegroundHover" Color="#ffdadada" />
   	<SolidColorBrush x:Key="SearchBoxWatermarkForegroundActive" Color="#ff2b2b2b" />
```

Compared to [Dark](https://github.com/stnkl/EverythingToolbar/blob/master/EverythingToolbar/Themes/Dark.xaml#L10-L11) theme: 
```xaml
    <SolidColorBrush x:Key="SearchBoxWatermarkForegroundHover" Color="#ffdadada" />
    <SolidColorBrush x:Key="SearchBoxWatermarkForegroundActive" Color="#ffdadada" />
```

**Comment by Horst12** [comment]
Thats right, I'm using the default Medium theme.

**Comment by stnkl** [comment]
Thank you, @kylo252! Looks better this way.

**Pull request merged**
