### PR TITLE
Fixed Issue #4 Taskbar Bug

### PR DESCRIPTION
**Pull request by Kamina-sama**
The added code prevents the Windows Taskbar from hiding while the searchbox has the keyboard focus.

### CODE REVIEW

**Comment by Kamina-sama** [comment]
I must test for other versions of Windows (Currently working with Windows 10). Also should check for other taskbar configurations. I will test some of this soon.

**Comment by stnkl** [comment]
Thanks for looking into this issue! I tried it and it doesn't exactly do what we need. It actually changes the auto-hide setting of the taskbar. This causes all other windows to snap into a different position. 

If you click the taskbar it stays visible until the taskbar loses focus again. I think this would be the correct approach to fix this. Unfortunately I couldn't get the taskbar to stay focused while at the same time having keyboard focus in the search box.

**Comment by Kamina-sama** [comment]
Hey man, I've been researching this issue and here is what I have so far:
Having taken in consideration what you've said, I was trying to reach a solution that doesn't change the auto-hide setting. So now the best candidate would be this: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showwindow
.However, I couldn't get it to work. Some googling made me realize this might be a bigger problem than what I've anticipated, have a look:
https://stackoverflow.com/questions/13468331/showwindow-function-doesnt-work-when-target-application-is-run-as-administrator
https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/4d2e1358-af95-4f4f-b239-68ec7e2525a9/uiaccess-in-manifest-files?forum=windowssecurity
If you have another idea, by all means tell me because I'm willing to help. Meanwhile I will keep throwing code at this thing hoping to bamboozle Windows somehow.

**Comment by stnkl** [comment]
I am closing this PR for now as it does not completely solve the problem. Hopefully we can find another fix for this.

**Pull request closed without merging**
